title: Harrison McCall
description: Offensive Security & Secure Systems Engineer | Founder of Zypheron
author: Harrison McCall
url: "https://kkingzero.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: /blog/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
